### ISSUE TITLE
Save 

### ISSUE THREAD

**Issue by mayaugusto7** [madzhuga/rails_workflow_demo#2]
Hi!

I have a problem on the create process file: concerns/rails_workflow/ has_context.rb in the line 14  context&.save 

![erro](https://user-images.githubusercontent.com/4804325/43975604-9382d6b4-9cb4-11e8-948a-a7a0d6aeb117.png)

Help me!

Thank you!

**Comment by madzhuga** [comment]
Hi! What version of ruby are you using? 
That's a save navigation operation from [2.3](http://nithinbekal.com/posts/ruby-2-3-features/)

**Comment by mayaugusto7** [comment]
Ok! 

I'm using version 2.2.

Thank you!
